language: node_js  #设置语言

cache: 
  - pandoc
  - hexo-renderer-pandoc

node_js: stable  #设置相应的版本

branches:
    only:
      - source

install:
  - wget ${pandoc}
  - sudo dpkg -i pandoc*.deb
  - npm install  #安装hexo及插件
  - npm install hexo-renderer-pandoc --save
  - npm install gulp -g
  - npm install gulp-minify-css gulp-uglify gulp-htmlmin gulp-htmlclean gulp --save

script:
  - hexo cl  #清除
  - hexo g  --config source/_data/next.yml #生成
  - gulp #压缩

after_script:
    - cd public
    - git init
    - git config user.name 'knightReigh'
    - git config user.email '12376953+knightReigh@users.noreply.github.com'
    - git add .
    - git commit -m 'Site updated'
    - git push -q -f "https://${GH_TOKEN}@${GH_REF}" master:master  
env: 
  global:
   - GH_REF: github.com/knightReigh/knightReigh.github.io.git  #设置GH_REF，注意更改yourname
   - pandoc: https://github.com/jgm/pandoc/releases/download/1.19.2.1/pandoc-1.19.2.1-1-amd64.deb

